import { Timestamp } from 'firebase/firestore';

export interface Note {
  id: string; // Document ID from Firestore
  title: string;
  content: string; // Markdown content
  projectId?: string | null; // Optional: ID of an associated project
  tags?: string[]; // Optional: Array of tag strings
  parentId?: string | null; // Optional: ID of a parent note for hierarchical structure
  createdAt: Timestamp;
  updatedAt: Timestamp;
  userId: string; // ID of the user who owns/created the note
}

// For creating a new note:
// - id is generated by Firestore
// - createdAt and updatedAt are set by serverTimestamp
// - userId must be provided
export type NewNoteData = Omit<Note, 'id' | 'createdAt' | 'updatedAt'>;

// For updating an existing note:
// - id is used to identify the document
// - userId and createdAt should not be updatable
// - updatedAt is set by serverTimestamp
export type UpdateNoteData = Partial<Omit<Note, 'id' | 'userId' | 'createdAt' | 'updatedAt'>>;
